// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeMaintenance = `-- name: CloseMaintenance :one
UPDATE maintenance
SET status = 'closed',
    closed_at = $1
WHERE id = $2 AND status = 'open'
RETURNING id, scooter_id, description, opened_at, closed_at, technician_id, status
`

type CloseMaintenanceParams struct {
	ClosedAt *time.Time `db:"closed_at"`
	ID       uuid.UUID  `db:"id"`
}

func (q *Queries) CloseMaintenance(ctx context.Context, arg CloseMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, closeMaintenance, arg.ClosedAt, arg.ID)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.ScooterID,
		&i.Description,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.TechnicianID,
		&i.Status,
	)
	return i, err
}

const countMaintenanceByScooter = `-- name: CountMaintenanceByScooter :one
SELECT COUNT(*) FROM maintenance WHERE scooter_id = $1
`

func (q *Queries) CountMaintenanceByScooter(ctx context.Context, scooterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceByScooter, scooterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenance = `-- name: CreateMaintenance :one
INSERT INTO maintenance (scooter_id, description, technician_id, status)
VALUES ($1, $2, $3, COALESCE($4, 'open'))
RETURNING id, scooter_id, description, opened_at, closed_at, technician_id, status
`

type CreateMaintenanceParams struct {
	ScooterID    uuid.UUID   `db:"scooter_id"`
	Description  string      `db:"description"`
	TechnicianID *uuid.UUID  `db:"technician_id"`
	Status       interface{} `db:"status"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, createMaintenance,
		arg.ScooterID,
		arg.Description,
		arg.TechnicianID,
		arg.Status,
	)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.ScooterID,
		&i.Description,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.TechnicianID,
		&i.Status,
	)
	return i, err
}

const getMaintenance = `-- name: GetMaintenance :one
SELECT id, scooter_id, description, opened_at, closed_at, technician_id, status
FROM maintenance WHERE id = $1
`

func (q *Queries) GetMaintenance(ctx context.Context, id uuid.UUID) (Maintenance, error) {
	row := q.db.QueryRow(ctx, getMaintenance, id)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.ScooterID,
		&i.Description,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.TechnicianID,
		&i.Status,
	)
	return i, err
}

const listMaintenanceByScooter = `-- name: ListMaintenanceByScooter :many
SELECT id, scooter_id, description, opened_at, closed_at, technician_id, status
FROM maintenance
WHERE scooter_id = $1
ORDER BY opened_at DESC
LIMIT $2 OFFSET $3
`

type ListMaintenanceByScooterParams struct {
	ScooterID uuid.UUID `db:"scooter_id"`
	Limit     int32     `db:"limit"`
	Offset    int32     `db:"offset"`
}

func (q *Queries) ListMaintenanceByScooter(ctx context.Context, arg ListMaintenanceByScooterParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, listMaintenanceByScooter, arg.ScooterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.ScooterID,
			&i.Description,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.TechnicianID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
