// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const closeMaintenance = `-- name: CloseMaintenance :one
UPDATE maintenance
SET status   = 'closed',
    end_date = $1
WHERE maintenance_id = $2 AND status = 'open'
RETURNING maintenance_id, scooter_id, technician_name, issue_description, repair_cost, start_date, end_date, status
`

type CloseMaintenanceParams struct {
	EndDate       *time.Time `db:"end_date"`
	MaintenanceID uuid.UUID  `db:"maintenance_id"`
}

func (q *Queries) CloseMaintenance(ctx context.Context, arg CloseMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, closeMaintenance, arg.EndDate, arg.MaintenanceID)
	var i Maintenance
	err := row.Scan(
		&i.MaintenanceID,
		&i.ScooterID,
		&i.TechnicianName,
		&i.IssueDescription,
		&i.RepairCost,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const countMaintenanceByScooter = `-- name: CountMaintenanceByScooter :one
SELECT COUNT(*) FROM maintenance WHERE scooter_id = $1
`

func (q *Queries) CountMaintenanceByScooter(ctx context.Context, scooterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceByScooter, scooterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenance = `-- name: CreateMaintenance :one
INSERT INTO maintenance (scooter_id, technician_name, issue_description, repair_cost, status)
VALUES ($1, $2, $3, $4, COALESCE($5, 'open'))
RETURNING maintenance_id, scooter_id, technician_name, issue_description, repair_cost, start_date, end_date, status
`

type CreateMaintenanceParams struct {
	ScooterID        uuid.UUID        `db:"scooter_id"`
	TechnicianName   string           `db:"technician_name"`
	IssueDescription string           `db:"issue_description"`
	RepairCost       *decimal.Decimal `db:"repair_cost"`
	Status           interface{}      `db:"status"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, createMaintenance,
		arg.ScooterID,
		arg.TechnicianName,
		arg.IssueDescription,
		arg.RepairCost,
		arg.Status,
	)
	var i Maintenance
	err := row.Scan(
		&i.MaintenanceID,
		&i.ScooterID,
		&i.TechnicianName,
		&i.IssueDescription,
		&i.RepairCost,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const getMaintenance = `-- name: GetMaintenance :one
SELECT maintenance_id, scooter_id, technician_name, issue_description, repair_cost, start_date, end_date, status
FROM maintenance WHERE maintenance_id = $1
`

func (q *Queries) GetMaintenance(ctx context.Context, maintenanceID uuid.UUID) (Maintenance, error) {
	row := q.db.QueryRow(ctx, getMaintenance, maintenanceID)
	var i Maintenance
	err := row.Scan(
		&i.MaintenanceID,
		&i.ScooterID,
		&i.TechnicianName,
		&i.IssueDescription,
		&i.RepairCost,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const listMaintenanceByScooter = `-- name: ListMaintenanceByScooter :many
SELECT maintenance_id, scooter_id, technician_name, issue_description, repair_cost, start_date, end_date, status
FROM maintenance
WHERE scooter_id = $1
ORDER BY start_date DESC
LIMIT $2 OFFSET $3
`

type ListMaintenanceByScooterParams struct {
	ScooterID uuid.UUID `db:"scooter_id"`
	Limit     int32     `db:"limit"`
	Offset    int32     `db:"offset"`
}

func (q *Queries) ListMaintenanceByScooter(ctx context.Context, arg ListMaintenanceByScooterParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, listMaintenanceByScooter, arg.ScooterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.MaintenanceID,
			&i.ScooterID,
			&i.TechnicianName,
			&i.IssueDescription,
			&i.RepairCost,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
