// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Maintenance struct {
	ID           uuid.UUID  `db:"id"`
	ScooterID    uuid.UUID  `db:"scooter_id"`
	Description  string     `db:"description"`
	OpenedAt     time.Time  `db:"opened_at"`
	ClosedAt     *time.Time `db:"closed_at"`
	TechnicianID *uuid.UUID `db:"technician_id"`
	Status       string     `db:"status"`
}

type PriceModel struct {
	ID            uuid.UUID        `db:"id"`
	Name          string           `db:"name"`
	PerMinuteRate decimal.Decimal  `db:"per_minute_rate"`
	UnlockFee     decimal.Decimal  `db:"unlock_fee"`
	DailyCap      *decimal.Decimal `db:"daily_cap"`
	Currency      string           `db:"currency"`
	CreatedAt     time.Time        `db:"created_at"`
	UpdatedAt     time.Time        `db:"updated_at"`
}

type Rental struct {
	ID           uuid.UUID       `db:"id"`
	UserID       uuid.UUID       `db:"user_id"`
	ScooterID    uuid.UUID       `db:"scooter_id"`
	PriceModelID uuid.UUID       `db:"price_model_id"`
	StartedAt    time.Time       `db:"started_at"`
	EndedAt      *time.Time      `db:"ended_at"`
	DistanceM    int32           `db:"distance_m"`
	TotalCost    decimal.Decimal `db:"total_cost"`
	Status       string          `db:"status"`
	CreatedAt    time.Time       `db:"created_at"`
	UpdatedAt    time.Time       `db:"updated_at"`
}

type Scooter struct {
	ID         uuid.UUID        `db:"id"`
	Code       string           `db:"code"`
	Model      string           `db:"model"`
	BatteryPct int32            `db:"battery_pct"`
	Status     string           `db:"status"`
	ZoneID     *uuid.UUID       `db:"zone_id"`
	Lat        *decimal.Decimal `db:"lat"`
	Lng        *decimal.Decimal `db:"lng"`
	CreatedAt  time.Time        `db:"created_at"`
	UpdatedAt  time.Time        `db:"updated_at"`
	DeletedAt  *time.Time       `db:"deleted_at"`
}

type User struct {
	ID            uuid.UUID       `db:"id"`
	Email         string          `db:"email"`
	Name          string          `db:"name"`
	Phone         *string         `db:"phone"`
	PasswordHash  *string         `db:"password_hash"`
	OauthID       *string         `db:"oauth_id"`
	Role          string          `db:"role"`
	WalletBalance decimal.Decimal `db:"wallet_balance"`
	CreatedAt     time.Time       `db:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at"`
	DeletedAt     *time.Time      `db:"deleted_at"`
}

type Zone struct {
	ID        uuid.UUID `db:"id"`
	Name      string    `db:"name"`
	Boundary  *string   `db:"boundary"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
