// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Maintenance struct {
	MaintenanceID    uuid.UUID        `db:"maintenance_id"`
	ScooterID        uuid.UUID        `db:"scooter_id"`
	TechnicianName   string           `db:"technician_name"`
	IssueDescription string           `db:"issue_description"`
	RepairCost       *decimal.Decimal `db:"repair_cost"`
	StartDate        time.Time        `db:"start_date"`
	EndDate          *time.Time       `db:"end_date"`
	Status           string           `db:"status"`
}

type PasswordResetToken struct {
	TokenID   uuid.UUID  `db:"token_id"`
	UserID    uuid.UUID  `db:"user_id"`
	TokenHash []byte     `db:"token_hash"`
	ExpiresAt time.Time  `db:"expires_at"`
	UsedAt    *time.Time `db:"used_at"`
	CreatedAt time.Time  `db:"created_at"`
}

type Payment struct {
	PaymentID         uuid.UUID       `db:"payment_id"`
	UserID            uuid.UUID       `db:"user_id"`
	RentalID          *uuid.UUID      `db:"rental_id"`
	Amount            decimal.Decimal `db:"amount"`
	Currency          string          `db:"currency"`
	PaymentMethod     string          `db:"payment_method"`
	Status            string          `db:"status"`
	ProviderPaymentID *string         `db:"provider_payment_id"`
	FailureReason     *string         `db:"failure_reason"`
	TransactionDate   time.Time       `db:"transaction_date"`
	UpdatedAt         time.Time       `db:"updated_at"`
	OfflineApprovedBy *uuid.UUID      `db:"offline_approved_by"`
	OfflineApprovedAt *time.Time      `db:"offline_approved_at"`
	IdempotencyKey    *string         `db:"idempotency_key"`
}

type PriceModel struct {
	PriceModelID   uuid.UUID        `db:"price_model_id"`
	Name           string           `db:"name"`
	UnlockFee      decimal.Decimal  `db:"unlock_fee"`
	PricePerMinute decimal.Decimal  `db:"price_per_minute"`
	Currency       string           `db:"currency"`
	DailyCap       *decimal.Decimal `db:"daily_cap"`
	CreatedAt      time.Time        `db:"created_at"`
	UpdatedAt      time.Time        `db:"updated_at"`
}

type Rental struct {
	RentalID     uuid.UUID        `db:"rental_id"`
	UserID       uuid.UUID        `db:"user_id"`
	ScooterID    uuid.UUID        `db:"scooter_id"`
	PriceModelID uuid.UUID        `db:"price_model_id"`
	StartTime    time.Time        `db:"start_time"`
	EndTime      *time.Time       `db:"end_time"`
	StartLat     *decimal.Decimal `db:"start_lat"`
	StartLon     *decimal.Decimal `db:"start_lon"`
	EndLat       *decimal.Decimal `db:"end_lat"`
	EndLon       *decimal.Decimal `db:"end_lon"`
	TotalCost    decimal.Decimal  `db:"total_cost"`
	Status       string           `db:"status"`
	DistanceM    int32            `db:"distance_m"`
	CreatedAt    time.Time        `db:"created_at"`
	UpdatedAt    time.Time        `db:"updated_at"`
}

type Scooter struct {
	ScooterID    uuid.UUID        `db:"scooter_id"`
	QrCode       string           `db:"qr_code"`
	BatteryLevel int32            `db:"battery_level"`
	Status       string           `db:"status"`
	ZoneID       *uuid.UUID       `db:"zone_id"`
	Model        string           `db:"model"`
	Lat          *decimal.Decimal `db:"lat"`
	Lng          *decimal.Decimal `db:"lng"`
	CreatedAt    time.Time        `db:"created_at"`
	UpdatedAt    time.Time        `db:"updated_at"`
	DeletedAt    *time.Time       `db:"deleted_at"`
}

type User struct {
	UserID           uuid.UUID  `db:"user_id"`
	FirstName        string     `db:"first_name"`
	LastName         string     `db:"last_name"`
	Email            string     `db:"email"`
	PhoneNumber      *string    `db:"phone_number"`
	RegistrationDate time.Time  `db:"registration_date"`
	Status           string     `db:"status"`
	Role             string     `db:"role"`
	PasswordHash     *string    `db:"password_hash"`
	OauthProvider    *string    `db:"oauth_provider"`
	OauthSubject     *string    `db:"oauth_subject"`
	StripeCustomerID *string    `db:"stripe_customer_id"`
	UpdatedAt        time.Time  `db:"updated_at"`
	LastLogoutAt     *time.Time `db:"last_logout_at"`
}

type WebhookEvent struct {
	EventID    string    `db:"event_id"`
	Type       string    `db:"type"`
	ReceivedAt time.Time `db:"received_at"`
	Payload    []byte    `db:"payload"`
}

type Zone struct {
	ZoneID       uuid.UUID       `db:"zone_id"`
	Name         string          `db:"name"`
	CenterLat    decimal.Decimal `db:"center_lat"`
	CenterLon    decimal.Decimal `db:"center_lon"`
	RadiusMeters int32           `db:"radius_meters"`
	ZoneType     string          `db:"zone_type"`
	CreatedAt    time.Time       `db:"created_at"`
	UpdatedAt    time.Time       `db:"updated_at"`
}
