// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const attachPaymentIntent = `-- name: AttachPaymentIntent :one
UPDATE payments
SET provider_payment_id = $1,
    status              = COALESCE($2, status),
    failure_reason      = $3,
    updated_at          = NOW()
WHERE payment_id = $4
RETURNING payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
`

type AttachPaymentIntentParams struct {
	ProviderPaymentID *string   `db:"provider_payment_id"`
	Status            *string   `db:"status"`
	FailureReason     *string   `db:"failure_reason"`
	PaymentID         uuid.UUID `db:"payment_id"`
}

func (q *Queries) AttachPaymentIntent(ctx context.Context, arg AttachPaymentIntentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, attachPaymentIntent,
		arg.ProviderPaymentID,
		arg.Status,
		arg.FailureReason,
		arg.PaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const countPaymentsByUser = `-- name: CountPaymentsByUser :one
SELECT COUNT(*) FROM payments WHERE user_id = $1
`

func (q *Queries) CountPaymentsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByUserSince = `-- name: CountPaymentsByUserSince :one
SELECT COUNT(*) FROM payments
WHERE user_id = $1
  AND transaction_date >= $2
`

type CountPaymentsByUserSinceParams struct {
	UserID uuid.UUID `db:"user_id"`
	Since  time.Time `db:"since"`
}

func (q *Queries) CountPaymentsByUserSince(ctx context.Context, arg CountPaymentsByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByUserSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOfflinePayment = `-- name: CreateOfflinePayment :one
INSERT INTO payments (
    user_id, rental_id, amount, currency, payment_method, status,
    offline_approved_by, offline_approved_at, idempotency_key
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'offline',
    'succeeded',
    $5,
    NOW(),
    $6
)
ON CONFLICT (idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
`

type CreateOfflinePaymentParams struct {
	UserID            uuid.UUID       `db:"user_id"`
	RentalID          *uuid.UUID      `db:"rental_id"`
	Amount            decimal.Decimal `db:"amount"`
	Currency          string          `db:"currency"`
	OfflineApprovedBy *uuid.UUID      `db:"offline_approved_by"`
	IdempotencyKey    *string         `db:"idempotency_key"`
}

func (q *Queries) CreateOfflinePayment(ctx context.Context, arg CreateOfflinePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createOfflinePayment,
		arg.UserID,
		arg.RentalID,
		arg.Amount,
		arg.Currency,
		arg.OfflineApprovedBy,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, 'USD'),
    COALESCE($5, 'card'),
    COALESCE($6, 'pending'),
    $7,
    $8
)
RETURNING payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
`

type CreatePaymentParams struct {
	UserID            uuid.UUID       `db:"user_id"`
	RentalID          *uuid.UUID      `db:"rental_id"`
	Amount            decimal.Decimal `db:"amount"`
	Currency          interface{}     `db:"currency"`
	PaymentMethod     interface{}     `db:"payment_method"`
	Status            interface{}     `db:"status"`
	ProviderPaymentID *string         `db:"provider_payment_id"`
	FailureReason     *string         `db:"failure_reason"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.RentalID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.ProviderPaymentID,
		arg.FailureReason,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
FROM payments
WHERE payment_id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, paymentID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, paymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
FROM payments
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
FROM payments
WHERE provider_payment_id = $1
`

func (q *Queries) GetPaymentByProviderID(ctx context.Context, providerPaymentID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const hasUnpaidRentals = `-- name: HasUnpaidRentals :one
SELECT EXISTS (
    SELECT 1
    FROM rentals r
    LEFT JOIN LATERAL (
        SELECT status
        FROM payments p
        WHERE p.rental_id = r.rental_id
        ORDER BY p.transaction_date DESC
        LIMIT 1
    ) lp ON TRUE
    WHERE r.user_id = $1
      AND (
            lp.status IN ('pending','failed')
        OR (lp.status IS NULL AND r.status = 'completed' AND r.total_cost > 0)
      )
) AS has_unpaid
`

func (q *Queries) HasUnpaidRentals(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnpaidRentals, userID)
	var has_unpaid bool
	err := row.Scan(&has_unpaid)
	return has_unpaid, err
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
FROM payments
WHERE user_id = $1
ORDER BY transaction_date DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByUserParams struct {
	UserID uuid.UUID `db:"user_id"`
	Limit  int32     `db:"limit"`
	Offset int32     `db:"offset"`
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.UserID,
			&i.RentalID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.ProviderPaymentID,
			&i.FailureReason,
			&i.TransactionDate,
			&i.UpdatedAt,
			&i.OfflineApprovedBy,
			&i.OfflineApprovedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUserSince = `-- name: ListPaymentsByUserSince :many
SELECT payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
FROM payments
WHERE user_id = $1
  AND transaction_date >= $2
ORDER BY transaction_date DESC
LIMIT $4 OFFSET $3
`

type ListPaymentsByUserSinceParams struct {
	UserID uuid.UUID `db:"user_id"`
	Since  time.Time `db:"since"`
	Offset int32     `db:"offset"`
	Limit  int32     `db:"limit"`
}

func (q *Queries) ListPaymentsByUserSince(ctx context.Context, arg ListPaymentsByUserSinceParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserSince,
		arg.UserID,
		arg.Since,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.UserID,
			&i.RentalID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.ProviderPaymentID,
			&i.FailureReason,
			&i.TransactionDate,
			&i.UpdatedAt,
			&i.OfflineApprovedBy,
			&i.OfflineApprovedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentByIDFailed = `-- name: MarkPaymentByIDFailed :one
UPDATE payments
SET status         = 'failed',
    failure_reason = $1,
    updated_at     = NOW()
WHERE payment_id = $2
RETURNING payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
`

type MarkPaymentByIDFailedParams struct {
	FailureReason *string   `db:"failure_reason"`
	PaymentID     uuid.UUID `db:"payment_id"`
}

func (q *Queries) MarkPaymentByIDFailed(ctx context.Context, arg MarkPaymentByIDFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentByIDFailed, arg.FailureReason, arg.PaymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status         = 'failed',
    failure_reason = $1,
    updated_at     = NOW()
WHERE provider_payment_id = $2
  AND status = 'pending'
RETURNING payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
`

type MarkPaymentFailedParams struct {
	FailureReason     *string `db:"failure_reason"`
	ProviderPaymentID *string `db:"provider_payment_id"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.FailureReason, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE payments
SET status     = 'succeeded',
    updated_at = NOW()
WHERE provider_payment_id = $1
  AND status = 'pending'
RETURNING payment_id, user_id, rental_id, amount, currency, payment_method, status, provider_payment_id, failure_reason, transaction_date, updated_at, offline_approved_by, offline_approved_at, idempotency_key
`

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, providerPaymentID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.RentalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureReason,
		&i.TransactionDate,
		&i.UpdatedAt,
		&i.OfflineApprovedBy,
		&i.OfflineApprovedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
