// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_models.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countPriceModels = `-- name: CountPriceModels :one
SELECT COUNT(*) FROM price_models
`

func (q *Queries) CountPriceModels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceModels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceModel = `-- name: CreatePriceModel :one
INSERT INTO price_models (name, per_minute_rate, unlock_fee, daily_cap, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, per_minute_rate, unlock_fee, daily_cap, currency, created_at, updated_at
`

type CreatePriceModelParams struct {
	Name          string           `db:"name"`
	PerMinuteRate decimal.Decimal  `db:"per_minute_rate"`
	UnlockFee     decimal.Decimal  `db:"unlock_fee"`
	DailyCap      *decimal.Decimal `db:"daily_cap"`
	Currency      string           `db:"currency"`
}

func (q *Queries) CreatePriceModel(ctx context.Context, arg CreatePriceModelParams) (PriceModel, error) {
	row := q.db.QueryRow(ctx, createPriceModel,
		arg.Name,
		arg.PerMinuteRate,
		arg.UnlockFee,
		arg.DailyCap,
		arg.Currency,
	)
	var i PriceModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PerMinuteRate,
		&i.UnlockFee,
		&i.DailyCap,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePriceModel = `-- name: DeletePriceModel :execrows
DELETE FROM price_models WHERE id = $1
`

func (q *Queries) DeletePriceModel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePriceModel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPriceModel = `-- name: GetPriceModel :one
SELECT id, name, per_minute_rate, unlock_fee, daily_cap, currency, created_at, updated_at
FROM price_models
WHERE id = $1
`

func (q *Queries) GetPriceModel(ctx context.Context, id uuid.UUID) (PriceModel, error) {
	row := q.db.QueryRow(ctx, getPriceModel, id)
	var i PriceModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PerMinuteRate,
		&i.UnlockFee,
		&i.DailyCap,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPriceModels = `-- name: ListPriceModels :many
SELECT id, name, per_minute_rate, unlock_fee, daily_cap, currency, created_at, updated_at
FROM price_models
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPriceModelsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListPriceModels(ctx context.Context, arg ListPriceModelsParams) ([]PriceModel, error) {
	rows, err := q.db.Query(ctx, listPriceModels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceModel{}
	for rows.Next() {
		var i PriceModel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PerMinuteRate,
			&i.UnlockFee,
			&i.DailyCap,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceModel = `-- name: UpdatePriceModel :one
UPDATE price_models
SET name = COALESCE($1, name),
    per_minute_rate = COALESCE($2, per_minute_rate),
    unlock_fee = COALESCE($3, unlock_fee),
    daily_cap = CASE WHEN $4::boolean THEN $5 ELSE daily_cap END,
    currency = COALESCE($6, currency),
    updated_at = NOW()
WHERE id = $7
RETURNING id, name, per_minute_rate, unlock_fee, daily_cap, currency, created_at, updated_at
`

type UpdatePriceModelParams struct {
	Name          *string          `db:"name"`
	PerMinuteRate *decimal.Decimal `db:"per_minute_rate"`
	UnlockFee     *decimal.Decimal `db:"unlock_fee"`
	DailyCapSet   bool             `db:"daily_cap_set"`
	DailyCap      *decimal.Decimal `db:"daily_cap"`
	Currency      *string          `db:"currency"`
	ID            uuid.UUID        `db:"id"`
}

func (q *Queries) UpdatePriceModel(ctx context.Context, arg UpdatePriceModelParams) (PriceModel, error) {
	row := q.db.QueryRow(ctx, updatePriceModel,
		arg.Name,
		arg.PerMinuteRate,
		arg.UnlockFee,
		arg.DailyCapSet,
		arg.DailyCap,
		arg.Currency,
		arg.ID,
	)
	var i PriceModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PerMinuteRate,
		&i.UnlockFee,
		&i.DailyCap,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
