// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AdjustWallet(ctx context.Context, arg AdjustWalletParams) (decimal.Decimal, error)
	CancelRental(ctx context.Context, id uuid.UUID) (int64, error)
	CloseMaintenance(ctx context.Context, arg CloseMaintenanceParams) (Maintenance, error)
	CountMaintenanceByScooter(ctx context.Context, scooterID uuid.UUID) (int64, error)
	CountPriceModels(ctx context.Context) (int64, error)
	CountRentalsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountScooters(ctx context.Context, arg CountScootersParams) (int64, error)
	CountZones(ctx context.Context) (int64, error)
	CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error)
	CreatePriceModel(ctx context.Context, arg CreatePriceModelParams) (PriceModel, error)
	CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error)
	CreateScooter(ctx context.Context, arg CreateScooterParams) (Scooter, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error)
	DeletePriceModel(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteZone(ctx context.Context, id uuid.UUID) (int64, error)
	EndRental(ctx context.Context, arg EndRentalParams) (Rental, error)
	FindNearbyScooters(ctx context.Context, arg FindNearbyScootersParams) ([]Scooter, error)
	GetMaintenance(ctx context.Context, id uuid.UUID) (Maintenance, error)
	GetPriceModel(ctx context.Context, id uuid.UUID) (PriceModel, error)
	GetRental(ctx context.Context, id uuid.UUID) (Rental, error)
	GetRentalForUpdate(ctx context.Context, id uuid.UUID) (Rental, error)
	GetScooter(ctx context.Context, id uuid.UUID) (Scooter, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWallet(ctx context.Context, id uuid.UUID) (decimal.Decimal, error)
	GetZone(ctx context.Context, id uuid.UUID) (Zone, error)
	ListMaintenanceByScooter(ctx context.Context, arg ListMaintenanceByScooterParams) ([]Maintenance, error)
	ListPriceModels(ctx context.Context, arg ListPriceModelsParams) ([]PriceModel, error)
	ListRentalsByUser(ctx context.Context, arg ListRentalsByUserParams) ([]Rental, error)
	ListScooters(ctx context.Context, arg ListScootersParams) ([]Scooter, error)
	ListZones(ctx context.Context, arg ListZonesParams) ([]Zone, error)
	RetireScooter(ctx context.Context, id uuid.UUID) (int64, error)
	SetScooterStatus(ctx context.Context, arg SetScooterStatusParams) (uuid.UUID, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	UpdatePriceModel(ctx context.Context, arg UpdatePriceModelParams) (PriceModel, error)
	UpdateScooter(ctx context.Context, arg UpdateScooterParams) (Scooter, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error)
}

var _ Querier = (*Queries)(nil)
