// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rentals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const cancelRental = `-- name: CancelRental :execrows
UPDATE rentals
SET status     = 'cancelled',
    updated_at = NOW()
WHERE rental_id = $1 AND status = 'active'
`

func (q *Queries) CancelRental(ctx context.Context, rentalID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRental, rentalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRentalsByUser = `-- name: CountRentalsByUser :one
SELECT COUNT(*) FROM rentals WHERE user_id = $1
`

func (q *Queries) CountRentalsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRentalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRental = `-- name: CreateRental :one
INSERT INTO rentals (user_id, scooter_id, price_model_id, start_time, start_lat, start_lon, status)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, NOW()),
    $5,
    $6,
    COALESCE($7, 'active')
)
RETURNING rental_id, user_id, scooter_id, price_model_id, start_time, end_time, start_lat, start_lon, end_lat, end_lon, total_cost, status, distance_m, created_at, updated_at
`

type CreateRentalParams struct {
	UserID       uuid.UUID        `db:"user_id"`
	ScooterID    uuid.UUID        `db:"scooter_id"`
	PriceModelID uuid.UUID        `db:"price_model_id"`
	StartTime    interface{}      `db:"start_time"`
	StartLat     *decimal.Decimal `db:"start_lat"`
	StartLon     *decimal.Decimal `db:"start_lon"`
	Status       interface{}      `db:"status"`
}

func (q *Queries) CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error) {
	row := q.db.QueryRow(ctx, createRental,
		arg.UserID,
		arg.ScooterID,
		arg.PriceModelID,
		arg.StartTime,
		arg.StartLat,
		arg.StartLon,
		arg.Status,
	)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLon,
		&i.EndLat,
		&i.EndLon,
		&i.TotalCost,
		&i.Status,
		&i.DistanceM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endRental = `-- name: EndRental :one
UPDATE rentals
SET status     = 'completed',
    end_time   = $1,
    end_lat    = $2,
    end_lon    = $3,
    distance_m = $4,
    total_cost = $5,
    updated_at = NOW()
WHERE rental_id = $6 AND status = 'active'
RETURNING rental_id, user_id, scooter_id, price_model_id, start_time, end_time, start_lat, start_lon, end_lat, end_lon, total_cost, status, distance_m, created_at, updated_at
`

type EndRentalParams struct {
	EndTime   *time.Time       `db:"end_time"`
	EndLat    *decimal.Decimal `db:"end_lat"`
	EndLon    *decimal.Decimal `db:"end_lon"`
	DistanceM int32            `db:"distance_m"`
	TotalCost decimal.Decimal  `db:"total_cost"`
	RentalID  uuid.UUID        `db:"rental_id"`
}

func (q *Queries) EndRental(ctx context.Context, arg EndRentalParams) (Rental, error) {
	row := q.db.QueryRow(ctx, endRental,
		arg.EndTime,
		arg.EndLat,
		arg.EndLon,
		arg.DistanceM,
		arg.TotalCost,
		arg.RentalID,
	)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLon,
		&i.EndLat,
		&i.EndLon,
		&i.TotalCost,
		&i.Status,
		&i.DistanceM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRental = `-- name: GetRental :one
SELECT rental_id, user_id, scooter_id, price_model_id, start_time, end_time, start_lat, start_lon, end_lat, end_lon, total_cost, status, distance_m, created_at, updated_at
FROM rentals
WHERE rental_id = $1
`

func (q *Queries) GetRental(ctx context.Context, rentalID uuid.UUID) (Rental, error) {
	row := q.db.QueryRow(ctx, getRental, rentalID)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLon,
		&i.EndLat,
		&i.EndLon,
		&i.TotalCost,
		&i.Status,
		&i.DistanceM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRentalForUpdate = `-- name: GetRentalForUpdate :one
SELECT rental_id, user_id, scooter_id, price_model_id, start_time, end_time, start_lat, start_lon, end_lat, end_lon, total_cost, status, distance_m, created_at, updated_at
FROM rentals
WHERE rental_id = $1
FOR UPDATE
`

func (q *Queries) GetRentalForUpdate(ctx context.Context, rentalID uuid.UUID) (Rental, error) {
	row := q.db.QueryRow(ctx, getRentalForUpdate, rentalID)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLon,
		&i.EndLat,
		&i.EndLon,
		&i.TotalCost,
		&i.Status,
		&i.DistanceM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRentalsByUser = `-- name: ListRentalsByUser :many
SELECT rental_id, user_id, scooter_id, price_model_id, start_time, end_time, start_lat, start_lon, end_lat, end_lon, total_cost, status, distance_m, created_at, updated_at
FROM rentals
WHERE user_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListRentalsByUserParams struct {
	UserID uuid.UUID `db:"user_id"`
	Limit  int32     `db:"limit"`
	Offset int32     `db:"offset"`
}

func (q *Queries) ListRentalsByUser(ctx context.Context, arg ListRentalsByUserParams) ([]Rental, error) {
	rows, err := q.db.Query(ctx, listRentalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rental{}
	for rows.Next() {
		var i Rental
		if err := rows.Scan(
			&i.RentalID,
			&i.UserID,
			&i.ScooterID,
			&i.PriceModelID,
			&i.StartTime,
			&i.EndTime,
			&i.StartLat,
			&i.StartLon,
			&i.EndLat,
			&i.EndLon,
			&i.TotalCost,
			&i.Status,
			&i.DistanceM,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
