// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rentals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const cancelRental = `-- name: CancelRental :execrows
UPDATE rentals
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CancelRental(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRental, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRentalsByUser = `-- name: CountRentalsByUser :one
SELECT COUNT(*) FROM rentals WHERE user_id = $1
`

func (q *Queries) CountRentalsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRentalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRental = `-- name: CreateRental :one
INSERT INTO rentals (user_id, scooter_id, price_model_id, started_at, status)
VALUES ($1, $2, $3, COALESCE($4, NOW()), COALESCE($5, 'active'))
RETURNING id, user_id, scooter_id, price_model_id, started_at, ended_at, distance_m, total_cost, status, created_at, updated_at
`

type CreateRentalParams struct {
	UserID       uuid.UUID   `db:"user_id"`
	ScooterID    uuid.UUID   `db:"scooter_id"`
	PriceModelID uuid.UUID   `db:"price_model_id"`
	StartedAt    interface{} `db:"started_at"`
	Status       interface{} `db:"status"`
}

func (q *Queries) CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error) {
	row := q.db.QueryRow(ctx, createRental,
		arg.UserID,
		arg.ScooterID,
		arg.PriceModelID,
		arg.StartedAt,
		arg.Status,
	)
	var i Rental
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceM,
		&i.TotalCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endRental = `-- name: EndRental :one
UPDATE rentals
SET status = 'completed',
    ended_at = $1,
    distance_m = $2,
    total_cost = $3,
    updated_at = NOW()
WHERE id = $4 AND status = 'active'
RETURNING id, user_id, scooter_id, price_model_id, started_at, ended_at, distance_m, total_cost, status, created_at, updated_at
`

type EndRentalParams struct {
	EndedAt   *time.Time      `db:"ended_at"`
	DistanceM int32           `db:"distance_m"`
	TotalCost decimal.Decimal `db:"total_cost"`
	ID        uuid.UUID       `db:"id"`
}

func (q *Queries) EndRental(ctx context.Context, arg EndRentalParams) (Rental, error) {
	row := q.db.QueryRow(ctx, endRental,
		arg.EndedAt,
		arg.DistanceM,
		arg.TotalCost,
		arg.ID,
	)
	var i Rental
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceM,
		&i.TotalCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRental = `-- name: GetRental :one
SELECT id, user_id, scooter_id, price_model_id, started_at, ended_at, distance_m, total_cost, status, created_at, updated_at
FROM rentals
WHERE id = $1
`

func (q *Queries) GetRental(ctx context.Context, id uuid.UUID) (Rental, error) {
	row := q.db.QueryRow(ctx, getRental, id)
	var i Rental
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceM,
		&i.TotalCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRentalForUpdate = `-- name: GetRentalForUpdate :one
SELECT id, user_id, scooter_id, price_model_id, started_at, ended_at, distance_m, total_cost, status, created_at, updated_at
FROM rentals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetRentalForUpdate(ctx context.Context, id uuid.UUID) (Rental, error) {
	row := q.db.QueryRow(ctx, getRentalForUpdate, id)
	var i Rental
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScooterID,
		&i.PriceModelID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceM,
		&i.TotalCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRentalsByUser = `-- name: ListRentalsByUser :many
SELECT id, user_id, scooter_id, price_model_id, started_at, ended_at, distance_m, total_cost, status, created_at, updated_at
FROM rentals
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListRentalsByUserParams struct {
	UserID uuid.UUID `db:"user_id"`
	Limit  int32     `db:"limit"`
	Offset int32     `db:"offset"`
}

func (q *Queries) ListRentalsByUser(ctx context.Context, arg ListRentalsByUserParams) ([]Rental, error) {
	rows, err := q.db.Query(ctx, listRentalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rental{}
	for rows.Next() {
		var i Rental
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScooterID,
			&i.PriceModelID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DistanceM,
			&i.TotalCost,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
