// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scooters.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countScooters = `-- name: CountScooters :one
SELECT COUNT(*) FROM scooters
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR zone_id = $2)
`

type CountScootersParams struct {
	Status *string    `db:"status"`
	ZoneID *uuid.UUID `db:"zone_id"`
}

func (q *Queries) CountScooters(ctx context.Context, arg CountScootersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScooters, arg.Status, arg.ZoneID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScooter = `-- name: CreateScooter :one
INSERT INTO scooters (qr_code, battery_level, status, zone_id, model, lat, lng)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING scooter_id, qr_code, battery_level, status, zone_id, model, lat, lng, created_at, updated_at, deleted_at
`

type CreateScooterParams struct {
	QrCode       string           `db:"qr_code"`
	BatteryLevel int32            `db:"battery_level"`
	Status       string           `db:"status"`
	ZoneID       *uuid.UUID       `db:"zone_id"`
	Model        string           `db:"model"`
	Lat          *decimal.Decimal `db:"lat"`
	Lng          *decimal.Decimal `db:"lng"`
}

func (q *Queries) CreateScooter(ctx context.Context, arg CreateScooterParams) (Scooter, error) {
	row := q.db.QueryRow(ctx, createScooter,
		arg.QrCode,
		arg.BatteryLevel,
		arg.Status,
		arg.ZoneID,
		arg.Model,
		arg.Lat,
		arg.Lng,
	)
	var i Scooter
	err := row.Scan(
		&i.ScooterID,
		&i.QrCode,
		&i.BatteryLevel,
		&i.Status,
		&i.ZoneID,
		&i.Model,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findNearbyScooters = `-- name: FindNearbyScooters :many
SELECT scooter_id, qr_code, battery_level, status, zone_id, model, lat, lng, created_at, updated_at, deleted_at
FROM scooters
WHERE status = 'available'
  AND deleted_at IS NULL
  AND lat IS NOT NULL
  AND lng IS NOT NULL
  AND (point(lng::float8, lat::float8) <@> point($1::float8, $2::float8)) * 1609.344 <= $3::float8
ORDER BY (point(lng::float8, lat::float8) <@> point($1::float8, $2::float8)) * 1609.344 ASC
LIMIT $4
`

type FindNearbyScootersParams struct {
	LngP    float64 `db:"lng_p"`
	LatP    float64 `db:"lat_p"`
	RadiusM float64 `db:"radius_m"`
	Lim     int32   `db:"lim"`
}

func (q *Queries) FindNearbyScooters(ctx context.Context, arg FindNearbyScootersParams) ([]Scooter, error) {
	rows, err := q.db.Query(ctx, findNearbyScooters,
		arg.LngP,
		arg.LatP,
		arg.RadiusM,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scooter{}
	for rows.Next() {
		var i Scooter
		if err := rows.Scan(
			&i.ScooterID,
			&i.QrCode,
			&i.BatteryLevel,
			&i.Status,
			&i.ZoneID,
			&i.Model,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScooter = `-- name: GetScooter :one
SELECT scooter_id, qr_code, battery_level, status, zone_id, model, lat, lng, created_at, updated_at, deleted_at
FROM scooters
WHERE scooter_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetScooter(ctx context.Context, scooterID uuid.UUID) (Scooter, error) {
	row := q.db.QueryRow(ctx, getScooter, scooterID)
	var i Scooter
	err := row.Scan(
		&i.ScooterID,
		&i.QrCode,
		&i.BatteryLevel,
		&i.Status,
		&i.ZoneID,
		&i.Model,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listScooters = `-- name: ListScooters :many
SELECT scooter_id, qr_code, battery_level, status, zone_id, model, lat, lng, created_at, updated_at, deleted_at
FROM scooters
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR zone_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListScootersParams struct {
	Status *string    `db:"status"`
	ZoneID *uuid.UUID `db:"zone_id"`
	Off    int32      `db:"off"`
	Lim    int32      `db:"lim"`
}

func (q *Queries) ListScooters(ctx context.Context, arg ListScootersParams) ([]Scooter, error) {
	rows, err := q.db.Query(ctx, listScooters,
		arg.Status,
		arg.ZoneID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scooter{}
	for rows.Next() {
		var i Scooter
		if err := rows.Scan(
			&i.ScooterID,
			&i.QrCode,
			&i.BatteryLevel,
			&i.Status,
			&i.ZoneID,
			&i.Model,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireScooter = `-- name: RetireScooter :execrows
UPDATE scooters
SET deleted_at = NOW(),
    status     = 'retired',
    updated_at = NOW()
WHERE scooter_id = $1 AND deleted_at IS NULL
`

func (q *Queries) RetireScooter(ctx context.Context, scooterID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, retireScooter, scooterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setScooterStatus = `-- name: SetScooterStatus :one
UPDATE scooters
SET status = $1,
    updated_at = NOW()
WHERE scooter_id = $2
  AND status = $3
  AND deleted_at IS NULL
RETURNING scooter_id
`

type SetScooterStatusParams struct {
	ToStatus   string    `db:"to_status"`
	ScooterID  uuid.UUID `db:"scooter_id"`
	FromStatus string    `db:"from_status"`
}

func (q *Queries) SetScooterStatus(ctx context.Context, arg SetScooterStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setScooterStatus, arg.ToStatus, arg.ScooterID, arg.FromStatus)
	var scooter_id uuid.UUID
	err := row.Scan(&scooter_id)
	return scooter_id, err
}

const updateScooter = `-- name: UpdateScooter :one
UPDATE scooters
SET model         = COALESCE($1, model),
    status        = COALESCE($2, status),
    zone_id       = CASE WHEN $3::boolean THEN $4 ELSE zone_id END,
    battery_level = COALESCE($5, battery_level),
    lat           = CASE WHEN $6::boolean THEN $7 ELSE lat END,
    lng           = CASE WHEN $8::boolean THEN $9 ELSE lng END,
    updated_at    = NOW()
WHERE scooter_id = $10 AND deleted_at IS NULL
RETURNING scooter_id, qr_code, battery_level, status, zone_id, model, lat, lng, created_at, updated_at, deleted_at
`

type UpdateScooterParams struct {
	Model        *string          `db:"model"`
	Status       *string          `db:"status"`
	ZoneIDSet    bool             `db:"zone_id_set"`
	ZoneID       *uuid.UUID       `db:"zone_id"`
	BatteryLevel *int32           `db:"battery_level"`
	LatSet       bool             `db:"lat_set"`
	Lat          *decimal.Decimal `db:"lat"`
	LngSet       bool             `db:"lng_set"`
	Lng          *decimal.Decimal `db:"lng"`
	ScooterID    uuid.UUID        `db:"scooter_id"`
}

func (q *Queries) UpdateScooter(ctx context.Context, arg UpdateScooterParams) (Scooter, error) {
	row := q.db.QueryRow(ctx, updateScooter,
		arg.Model,
		arg.Status,
		arg.ZoneIDSet,
		arg.ZoneID,
		arg.BatteryLevel,
		arg.LatSet,
		arg.Lat,
		arg.LngSet,
		arg.Lng,
		arg.ScooterID,
	)
	var i Scooter
	err := row.Scan(
		&i.ScooterID,
		&i.QrCode,
		&i.BatteryLevel,
		&i.Status,
		&i.ZoneID,
		&i.Model,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
