// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const adjustWallet = `-- name: AdjustWallet :one
UPDATE users
SET wallet_balance = wallet_balance + $1,
    updated_at = NOW()
WHERE id = $2
  AND deleted_at IS NULL
  AND wallet_balance + $1 >= 0
RETURNING wallet_balance
`

type AdjustWalletParams struct {
	Delta decimal.Decimal `db:"delta"`
	ID    uuid.UUID       `db:"id"`
}

func (q *Queries) AdjustWallet(ctx context.Context, arg AdjustWalletParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, adjustWallet, arg.Delta, arg.ID)
	var wallet_balance decimal.Decimal
	err := row.Scan(&wallet_balance)
	return wallet_balance, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, phone, password_hash, oauth_id, role, wallet_balance)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, name, phone, password_hash, oauth_id, role, wallet_balance, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email         string          `db:"email"`
	Name          string          `db:"name"`
	Phone         *string         `db:"phone"`
	PasswordHash  *string         `db:"password_hash"`
	OauthID       *string         `db:"oauth_id"`
	Role          string          `db:"role"`
	WalletBalance decimal.Decimal `db:"wallet_balance"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.PasswordHash,
		arg.OauthID,
		arg.Role,
		arg.WalletBalance,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.OauthID,
		&i.Role,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, phone, password_hash, oauth_id, role, wallet_balance, created_at, updated_at, deleted_at
FROM users
WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.OauthID,
		&i.Role,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, phone, password_hash, oauth_id, role, wallet_balance, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.OauthID,
		&i.Role,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT wallet_balance
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWallet(ctx context.Context, id uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var wallet_balance decimal.Decimal
	err := row.Scan(&wallet_balance)
	return wallet_balance, err
}

const setUserRole = `-- name: SetUserRole :execrows
UPDATE users
SET role = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type SetUserRoleParams struct {
	Role string    `db:"role"`
	ID   uuid.UUID `db:"id"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserRole, arg.Role, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, email, name, phone, password_hash, oauth_id, role, wallet_balance, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Name  *string   `db:"name"`
	Phone *string   `db:"phone"`
	ID    uuid.UUID `db:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Phone, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.OauthID,
		&i.Role,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
