// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email, phone_number, password_hash, oauth_provider, oauth_subject, role, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9, 'active'))
RETURNING user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
`

type CreateUserParams struct {
	FirstName     string      `db:"first_name"`
	LastName      string      `db:"last_name"`
	Email         string      `db:"email"`
	PhoneNumber   *string     `db:"phone_number"`
	PasswordHash  *string     `db:"password_hash"`
	OauthProvider *string     `db:"oauth_provider"`
	OauthSubject  *string     `db:"oauth_subject"`
	Role          string      `db:"role"`
	Status        interface{} `db:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.OauthProvider,
		arg.OauthSubject,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
FROM users
WHERE LOWER(email) = LOWER($1) AND status <> 'deleted'
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
FROM users
WHERE user_id = $1 AND status <> 'deleted'
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
FROM users
WHERE oauth_provider = $1 AND oauth_subject = $2 AND status <> 'deleted'
`

type GetUserByOAuthParams struct {
	OauthProvider *string `db:"oauth_provider"`
	OauthSubject  *string `db:"oauth_subject"`
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuth, arg.OauthProvider, arg.OauthSubject)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}

const linkUserOAuth = `-- name: LinkUserOAuth :one
UPDATE users
SET oauth_provider = $1,
    oauth_subject  = $2,
    updated_at     = NOW()
WHERE user_id = $3 AND status <> 'deleted'
RETURNING user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
`

type LinkUserOAuthParams struct {
	OauthProvider *string   `db:"oauth_provider"`
	OauthSubject  *string   `db:"oauth_subject"`
	UserID        uuid.UUID `db:"user_id"`
}

func (q *Queries) LinkUserOAuth(ctx context.Context, arg LinkUserOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, linkUserOAuth, arg.OauthProvider, arg.OauthSubject, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}

const setStripeCustomerID = `-- name: SetStripeCustomerID :one
UPDATE users
SET stripe_customer_id = $1,
    updated_at = NOW()
WHERE user_id = $2 AND status <> 'deleted'
RETURNING user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
`

type SetStripeCustomerIDParams struct {
	StripeCustomerID *string   `db:"stripe_customer_id"`
	UserID           uuid.UUID `db:"user_id"`
}

func (q *Queries) SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) (User, error) {
	row := q.db.QueryRow(ctx, setStripeCustomerID, arg.StripeCustomerID, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :execrows
UPDATE users
SET role = $1,
    updated_at = NOW()
WHERE user_id = $2 AND status <> 'deleted'
`

type SetUserRoleParams struct {
	Role   string    `db:"role"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserRole, arg.Role, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET status = 'deleted',
    updated_at = NOW()
WHERE user_id = $1 AND status <> 'deleted'
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name   = COALESCE($1, first_name),
    last_name    = COALESCE($2, last_name),
    phone_number = COALESCE($3, phone_number),
    updated_at   = NOW()
WHERE user_id = $4 AND status <> 'deleted'
RETURNING user_id, first_name, last_name, email, phone_number, registration_date, status, role, password_hash, oauth_provider, oauth_subject, stripe_customer_id, updated_at, last_logout_at
`

type UpdateUserParams struct {
	FirstName   *string   `db:"first_name"`
	LastName    *string   `db:"last_name"`
	PhoneNumber *string   `db:"phone_number"`
	UserID      uuid.UUID `db:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.RegistrationDate,
		&i.Status,
		&i.Role,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.StripeCustomerID,
		&i.UpdatedAt,
		&i.LastLogoutAt,
	)
	return i, err
}
