// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlc

import (
	"context"
)

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (event_id, type, payload)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type InsertWebhookEventParams struct {
	EventID string `db:"event_id"`
	Type    string `db:"type"`
	Payload []byte `db:"payload"`
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.EventID, arg.Type, arg.Payload)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}
