// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countZones = `-- name: CountZones :one
SELECT COUNT(*) FROM zones
`

func (q *Queries) CountZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countZones)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO zones (name, boundary)
VALUES ($1, $2)
RETURNING id, name, boundary, created_at, updated_at
`

type CreateZoneParams struct {
	Name     string  `db:"name"`
	Boundary *string `db:"boundary"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone, arg.Name, arg.Boundary)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Boundary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZone = `-- name: DeleteZone :execrows
DELETE FROM zones WHERE id = $1
`

func (q *Queries) DeleteZone(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteZone, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getZone = `-- name: GetZone :one
SELECT id, name, boundary, created_at, updated_at
FROM zones
WHERE id = $1
`

func (q *Queries) GetZone(ctx context.Context, id uuid.UUID) (Zone, error) {
	row := q.db.QueryRow(ctx, getZone, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Boundary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT id, name, boundary, created_at, updated_at
FROM zones
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListZonesParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListZones(ctx context.Context, arg ListZonesParams) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZones, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Boundary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name = COALESCE($1, name),
    boundary = COALESCE($2, boundary),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, boundary, created_at, updated_at
`

type UpdateZoneParams struct {
	Name     *string   `db:"name"`
	Boundary *string   `db:"boundary"`
	ID       uuid.UUID `db:"id"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone, arg.Name, arg.Boundary, arg.ID)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Boundary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
