// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countZones = `-- name: CountZones :one
SELECT COUNT(*) FROM zones
`

func (q *Queries) CountZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countZones)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO zones (name, center_lat, center_lon, radius_meters, zone_type)
VALUES ($1, $2, $3, $4, COALESCE($5, 'service'))
RETURNING zone_id, name, center_lat, center_lon, radius_meters, zone_type, created_at, updated_at
`

type CreateZoneParams struct {
	Name         string          `db:"name"`
	CenterLat    decimal.Decimal `db:"center_lat"`
	CenterLon    decimal.Decimal `db:"center_lon"`
	RadiusMeters int32           `db:"radius_meters"`
	ZoneType     interface{}     `db:"zone_type"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.Name,
		arg.CenterLat,
		arg.CenterLon,
		arg.RadiusMeters,
		arg.ZoneType,
	)
	var i Zone
	err := row.Scan(
		&i.ZoneID,
		&i.Name,
		&i.CenterLat,
		&i.CenterLon,
		&i.RadiusMeters,
		&i.ZoneType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZone = `-- name: DeleteZone :execrows
DELETE FROM zones WHERE zone_id = $1
`

func (q *Queries) DeleteZone(ctx context.Context, zoneID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteZone, zoneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getZone = `-- name: GetZone :one
SELECT zone_id, name, center_lat, center_lon, radius_meters, zone_type, created_at, updated_at
FROM zones
WHERE zone_id = $1
`

func (q *Queries) GetZone(ctx context.Context, zoneID uuid.UUID) (Zone, error) {
	row := q.db.QueryRow(ctx, getZone, zoneID)
	var i Zone
	err := row.Scan(
		&i.ZoneID,
		&i.Name,
		&i.CenterLat,
		&i.CenterLon,
		&i.RadiusMeters,
		&i.ZoneType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT zone_id, name, center_lat, center_lon, radius_meters, zone_type, created_at, updated_at
FROM zones
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListZonesParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListZones(ctx context.Context, arg ListZonesParams) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZones, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ZoneID,
			&i.Name,
			&i.CenterLat,
			&i.CenterLon,
			&i.RadiusMeters,
			&i.ZoneType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name          = COALESCE($1, name),
    center_lat    = COALESCE($2, center_lat),
    center_lon    = COALESCE($3, center_lon),
    radius_meters = COALESCE($4, radius_meters),
    zone_type     = COALESCE($5, zone_type),
    updated_at    = NOW()
WHERE zone_id = $6
RETURNING zone_id, name, center_lat, center_lon, radius_meters, zone_type, created_at, updated_at
`

type UpdateZoneParams struct {
	Name         *string          `db:"name"`
	CenterLat    *decimal.Decimal `db:"center_lat"`
	CenterLon    *decimal.Decimal `db:"center_lon"`
	RadiusMeters *int32           `db:"radius_meters"`
	ZoneType     *string          `db:"zone_type"`
	ZoneID       uuid.UUID        `db:"zone_id"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.Name,
		arg.CenterLat,
		arg.CenterLon,
		arg.RadiusMeters,
		arg.ZoneType,
		arg.ZoneID,
	)
	var i Zone
	err := row.Scan(
		&i.ZoneID,
		&i.Name,
		&i.CenterLat,
		&i.CenterLon,
		&i.RadiusMeters,
		&i.ZoneType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
